name: CI Workflow

on:
  push:
    branches: [ main, mas-ad ]
  pull_request:
    branches: [ main ]

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.repository_owner, 'bf2fc6cc711aee1a0c2a')
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{matrix.node-version}}

      # Open-Source Machine emulator that allows you to emulate multiple CPU architectures on your machine
      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v1
        
      # Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        id: buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Installing dependencies
        run: npm install

      - name: Run production build
        run: npm run build

      - name: Set Image Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "IMAGE_TAG=latest-snapshot" >> $GITHUB_ENV

      - name: Login to DockerHub Registry
        if: github.event_name == 'push'
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: BBuild and Publish Multi-Arch Docker Images
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
         context: ./
         file: ./Dockerfile
         platforms: ${{env.PLATFORMS}}
         push: true
         tags: |
           docker.io/apicurio/api-designer-ads:${{env.IMAGE_TAG}}
           quay.io/apicurio/api-designer-ads:${{env.IMAGE_TAG}}
