name: Verify Workflow

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-project:
    runs-on: ubuntu-latest
    if: contains(github.repository_owner, 'bf2fc6cc711aee1a0c2a')
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{matrix.node-version}}
     
      - name: Installing dependencies
        run: npm install

      - name: Clean dist
        run: npm run prebuild

      - name: Run production build
        run: npm run build


  publish-snapshot-image:
    needs: [build-project]
    if: contains(github.repository_owner, 'bf2fc6cc711aee1a0c2a') && github.event_name == 'push'
    uses: ./.github/workflows/release-images.yaml
    with:
      image-tag: "latest-snapshot"